[2025-02-11T07:32:56.357+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_etl.dwh_to_feature_store manual__2025-02-11T07:32:54.453926+00:00 [queued]>
[2025-02-11T07:32:56.365+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_etl.dwh_to_feature_store manual__2025-02-11T07:32:54.453926+00:00 [queued]>
[2025-02-11T07:32:56.366+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-11T07:32:56.374+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): dwh_to_feature_store> on 2025-02-11 07:32:54.453926+00:00
[2025-02-11T07:32:56.379+0000] {standard_task_runner.py:57} INFO - Started process 1796 to run task
[2025-02-11T07:32:56.383+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'loan_etl', 'dwh_to_feature_store', 'manual__2025-02-11T07:32:54.453926+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/batch_processing.py', '--cfg-path', '/tmp/tmpl_0cwiv4']
[2025-02-11T07:32:56.389+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask dwh_to_feature_store
[2025-02-11T07:32:56.433+0000] {task_command.py:415} INFO - Running <TaskInstance: loan_etl.dwh_to_feature_store manual__2025-02-11T07:32:54.453926+00:00 [running]> on host 94963e7d153a
[2025-02-11T07:32:56.496+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='loan_etl' AIRFLOW_CTX_TASK_ID='dwh_to_feature_store' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T07:32:54.453926+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T07:32:54.453926+00:00'
[2025-02-11T07:33:12.898+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch_processing.py", line 17, in etl_dwh_to_feature_store
    etl.execute(app_name="ETL from data warehouse to feature store", table_name="loan")
  File "/opt/airflow/dags/processing/batch/loan_approval_classification/loan_etl.py", line 67, in execute
    df = self.extract(spark, table_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processing/batch/loan_approval_classification/loan_etl.py", line 44, in extract
    .load()
     ^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 314, in load
    return self._df(self._jreader.load())
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.IllegalArgumentException: Option 'dbtable' or 'query' is required.
[2025-02-11T07:33:12.998+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=loan_etl, task_id=dwh_to_feature_store, execution_date=20250211T073254, start_date=20250211T073256, end_date=20250211T073312
[2025-02-11T07:33:13.050+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 71 for task dwh_to_feature_store (Option 'dbtable' or 'query' is required.; 1796)
[2025-02-11T07:33:13.106+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-11T07:33:13.154+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
