[2025-02-11T02:44:08.322+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_etl.dwh_to_feature_store manual__2025-02-11T02:44:07.034342+00:00 [queued]>
[2025-02-11T02:44:08.326+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_etl.dwh_to_feature_store manual__2025-02-11T02:44:07.034342+00:00 [queued]>
[2025-02-11T02:44:08.326+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-11T02:44:08.331+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): dwh_to_feature_store> on 2025-02-11 02:44:07.034342+00:00
[2025-02-11T02:44:08.334+0000] {standard_task_runner.py:57} INFO - Started process 226 to run task
[2025-02-11T02:44:08.336+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'loan_etl', 'dwh_to_feature_store', 'manual__2025-02-11T02:44:07.034342+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/batch_processing.py', '--cfg-path', '/tmp/tmpenc_qjs_']
[2025-02-11T02:44:08.338+0000] {standard_task_runner.py:85} INFO - Job 67: Subtask dwh_to_feature_store
[2025-02-11T02:44:08.358+0000] {task_command.py:415} INFO - Running <TaskInstance: loan_etl.dwh_to_feature_store manual__2025-02-11T02:44:07.034342+00:00 [running]> on host 94963e7d153a
[2025-02-11T02:44:08.429+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='loan_etl' AIRFLOW_CTX_TASK_ID='dwh_to_feature_store' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T02:44:07.034342+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T02:44:07.034342+00:00'
[2025-02-11T02:44:08.430+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch_processing.py", line 16, in etl_dwh_to_feature_store
    etl = LoanApprovalETL()
          ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processing/batch/loan_approval_classification/loan_etl.py", line 16, in __init__
    self.__host = get_env_variable("SILVER_HOST")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processing/utils.py", line 7, in get_env_variable
    raise ValueError(f"Variable '{variable_name}' not found in environment.")
ValueError: Variable 'SILVER_HOST' not found in environment.
[2025-02-11T02:44:08.435+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=loan_etl, task_id=dwh_to_feature_store, execution_date=20250211T024407, start_date=20250211T024408, end_date=20250211T024408
[2025-02-11T02:44:08.443+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 67 for task dwh_to_feature_store (Variable 'SILVER_HOST' not found in environment.; 226)
[2025-02-11T02:44:08.473+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-11T02:44:08.483+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
